export const defaultTheme = {
  colors: {
    white: '#FFFFFF',
    background: '#FAFAFA',
    yellow: '#DBAC2C',
    'yellow-dark': '#C47F17',
    'yellow-light': '#F1E9C9',
    purple: '#8047F8',
    'purple-light': '#EBE5F9',
    'purple-dark': '#4B2995',
    'base-title': '#272221',
    'base-subtitle': '#403937',
    'base-text': '#574F4D',
    'base-label': '#8D8686',
    'base-hover': '#D7D5D5',
    'base-button': '#E6E5E5',
    'base-input': '#EDEDED',
    'base-card': '#F3F2F2',
  },
  textSizes: {
    'title-xl': '4.8rem',
    'title-l': '3.2rem',
    'title-m': '2.4rem',
    'title-s': '2rem',
    'title-xs': '1.8rem',
    'text-l': '2rem',
    'text-m': '1.6rem',
    'text-s': '1.4rem',
    'text-bold-xs': '1.2rem',
    'tag-bold': '1rem',
    'button-bold-g': '1.4rem',
    'button-regular-m': '1.4rem',
  },
  breakpoints: {
    XS: 0,
    SM: '576px',
    MD: '768px',
    LG: '992px',
    XL: '1200px',
  },
  fonts: {
    default: "'Roboto', sans-serif",
    title: "'Baloo 2', cursive",
  },
};
